Repository MarshallAsch/veil-droid, pull requests merged in 2018-06, with the labels that each got.

#16 11 dashboard ui
  app/src/main/java/ca/marshallasch/veil/FragmentDashBoard.java
  app/src/main/java/ca/marshallasch/veil/FragmentLogin.java
  app/src/main/res/drawable/avatar.png
  app/src/main/res/drawable/background.png
  app/src/main/res/drawable/profilepic.png
  app/src/main/res/layout/fragment_dash_board.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/values/colors.xml
Labels: QA

#20 7 database
  .idea/caches/build_file_checksums.ser
  .idea/encodings.xml
  .idea/misc.xml
  app/build.gradle
  app/src/androidTest/java/ca/marshallasch/veil/database/DatabaseTest.java
  app/src/main/java/ca/marshallasch/veil/database/BlockContract.java
  app/src/main/java/ca/marshallasch/veil/database/Database.java
  app/src/main/java/ca/marshallasch/veil/database/KnownHashesContract.java
  app/src/main/java/ca/marshallasch/veil/database/NotificationContract.java
  app/src/main/java/ca/marshallasch/veil/database/UserContract.java
  app/src/main/java/ca/marshallasch/veil/utilities/Util.java
  app/src/main/proto/dht.proto
  app/src/main/res/values/strings.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: QA

#17 12 forums page ui
  .idea/caches/build_file_checksums.ser
  .idea/codeStyles/Project.xml
  .idea/misc.xml
  app/src/main/assets/rightmesh.json
  app/src/main/java/ca/marshallasch/veil/Data.java
  app/src/main/java/ca/marshallasch/veil/FragmentDashBoard.java
  app/src/main/java/ca/marshallasch/veil/FragmentDiscoverForums.java
  app/src/main/java/ca/marshallasch/veil/PostListAdapter.java
  app/src/main/res/layout/fragment_discover_forums.xml
  app/src/main/res/layout/list_cell.xml
Labels: QA

#28 25 Account Logic
  app/src/androidTest/java/ca/marshallasch/veil/database/DatabaseTest.java
  app/src/main/java/ca/marshallasch/veil/FragmentDashBoard.java
  app/src/main/java/ca/marshallasch/veil/FragmentLogin.java
  app/src/main/java/ca/marshallasch/veil/FragmentSignUp.java
  app/src/main/java/ca/marshallasch/veil/MainActivity.java
  app/src/main/java/ca/marshallasch/veil/database/Database.java
  app/src/main/java/ca/marshallasch/veil/database/Migrations.java
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/values/strings.xml
Labels: QA

#29 moved hidekeyboard function into utils + added hidekeyboard functions…
  app/src/main/java/ca/marshallasch/veil/FragmentLogin.java
  app/src/main/java/ca/marshallasch/veil/FragmentSignUp.java
  app/src/main/java/ca/marshallasch/veil/utilities/Util.java
Labels: QA

#30 Added a basic splash screen
  app/src/main/AndroidManifest.xml
  app/src/main/java/ca/marshallasch/veil/MainActivity.java
  app/src/main/res/drawable/launch_screen.xml
  app/src/main/res/values/styles.xml
Labels: QA

#32 refactored xml and removed nested layouts + fixed issue wwhere log ou…
  app/src/main/res/layout/fragment_dash_board.xml
Labels: QA

#33 31 data storage interface creation
  app/src/main/java/ca/marshallasch/veil/ForumStorage.java
Labels: QA

#38 fixed issue where logout button retained the backstack causing unwant…
  app/src/main/java/ca/marshallasch/veil/FragmentDashBoard.java
  app/src/main/java/ca/marshallasch/veil/FragmentSignUp.java
Labels: QA

#39 added UI and functionality for viewing post button
  app/src/main/java/ca/marshallasch/veil/FragmentDiscoverForums.java
  app/src/main/java/ca/marshallasch/veil/FragmentViewPost.java
  app/src/main/java/ca/marshallasch/veil/PostListAdapter.java
  app/src/main/res/layout/fragment_view_post.xml
  app/src/main/res/layout/list_cell.xml
  app/src/main/res/values/strings.xml
Labels: QA

#35 34 Login hotfix
  app/src/main/java/ca/marshallasch/veil/FragmentLogin.java
Labels: Priority: Critical, Status: Review Needed

#41 40 in memory data store
  app/src/main/java/ca/marshallasch/veil/ForumStorage.java
  app/src/main/java/ca/marshallasch/veil/MemoryStore.java
  app/src/main/java/ca/marshallasch/veil/exceptions/TooManyResultsException.java
  app/src/main/java/ca/marshallasch/veil/utilities/Util.java
  app/src/main/proto/dht.proto
Labels: Status: Review Needed

#46 44 hard coded strings.
  app/build.gradle
  app/src/androidTest/java/ca/marshallasch/veil/database/DatabaseTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/ca/marshallasch/veil/FragmentDashBoard.java
  app/src/main/java/ca/marshallasch/veil/FragmentDiscoverForums.java
  app/src/main/java/ca/marshallasch/veil/FragmentViewPost.java
  app/src/main/java/ca/marshallasch/veil/PostListAdapter.java
  app/src/main/java/ca/marshallasch/veil/database/Database.java
  app/src/main/res/drawable/profile_picture.png
  app/src/main/res/layout/fragment_dash_board.xml
  app/src/main/res/layout/fragment_landing.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_view_post.xml
  app/src/main/res/layout/list_cell.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: Status: Review Needed

#45 23 create post
  .idea/assetWizardSettings.xml
  app/src/main/java/ca/marshallasch/veil/FragmentCreatePost.java
  app/src/main/java/ca/marshallasch/veil/FragmentDashBoard.java
  app/src/main/java/ca/marshallasch/veil/database/KnownHashesContract.java
  app/src/main/res/drawable/ic_add_black_24dp.xml
  app/src/main/res/layout/fragment_create_post.xml
  app/src/main/res/layout/fragment_dash_board.xml
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Needed

#48 42 memory store unit test
  app/src/main/java/ca/marshallasch/veil/ForumStorage.java
  app/src/main/java/ca/marshallasch/veil/MemoryStore.java
  app/src/main/java/ca/marshallasch/veil/comparators/CommentPairComparator.java
  app/src/main/java/ca/marshallasch/veil/comparators/PostPairComparator.java
  app/src/main/java/ca/marshallasch/veil/utilities/Util.java
  app/src/main/proto/dht.proto
  app/src/test/java/ca/marshallasch/veil/MemoryStoreTest.java
  app/src/test/java/ca/marshallasch/veil/utilities/UtilTest.java
Labels: Status: Review Needed

#49 43 fragment support migration
  app/src/main/java/ca/marshallasch/veil/FragmentCreatePost.java
  app/src/main/java/ca/marshallasch/veil/FragmentDashBoard.java
  app/src/main/java/ca/marshallasch/veil/FragmentDiscoverForums.java
  app/src/main/java/ca/marshallasch/veil/FragmentLanding.java
  app/src/main/java/ca/marshallasch/veil/FragmentLogin.java
  app/src/main/java/ca/marshallasch/veil/FragmentSignUp.java
  app/src/main/java/ca/marshallasch/veil/FragmentViewPost.java
  app/src/main/java/ca/marshallasch/veil/MainActivity.java
Labels: Status: Review Needed

#54 53 known post db
  app/src/androidTest/java/ca/marshallasch/veil/database/DatabaseTest.java
  app/src/main/java/ca/marshallasch/veil/FragmentCreatePost.java
  app/src/main/java/ca/marshallasch/veil/database/Database.java
  app/src/main/java/ca/marshallasch/veil/database/KnownPostsContract.java
  app/src/main/java/ca/marshallasch/veil/database/Migrations.java
  app/src/main/java/ca/marshallasch/veil/database/UserContract.java
Labels: Status: Review Needed

#55 47 delegate data store
  app/src/main/java/ca/marshallasch/veil/DataStore.java
  app/src/main/java/ca/marshallasch/veil/ForumStorage.java
  app/src/main/java/ca/marshallasch/veil/FragmentCreatePost.java
  app/src/main/java/ca/marshallasch/veil/FragmentDiscoverForums.java
  app/src/main/java/ca/marshallasch/veil/FragmentSignUp.java
  app/src/main/java/ca/marshallasch/veil/FragmentViewPost.java
  app/src/main/java/ca/marshallasch/veil/HashTableStore.java
  app/src/main/java/ca/marshallasch/veil/MainActivity.java
  app/src/main/java/ca/marshallasch/veil/PostListAdapter.java
  app/src/main/java/ca/marshallasch/veil/database/Database.java
  app/src/main/java/ca/marshallasch/veil/utilities/Util.java
  app/src/main/proto/sync.proto
  app/src/test/java/ca/marshallasch/veil/HashTableStoreTest.java
Labels: Status: Review Needed

#56 51 update post view
  app/src/main/java/ca/marshallasch/veil/CommentListAdapter.java
  app/src/main/java/ca/marshallasch/veil/FragmentCreatePost.java
  app/src/main/java/ca/marshallasch/veil/FragmentViewPost.java
  app/src/main/res/layout/comment_item.xml
  app/src/main/res/layout/fragment_view_post.xml
  app/src/main/res/layout/list_cell.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Needed

#64 63 updated RM version
  app/build.gradle
Labels: Status: Review Needed

#57 5 peer discovery protocal
  app/src/main/java/ca/marshallasch/veil/DataStore.java
  app/src/main/java/ca/marshallasch/veil/HashTableStore.java
  app/src/main/java/ca/marshallasch/veil/MainActivity.java
  app/src/main/java/ca/marshallasch/veil/comparators/EntryComparator.java
  app/src/main/java/ca/marshallasch/veil/database/Database.java
  app/src/main/java/ca/marshallasch/veil/serializer/MapSerializer.java
  app/src/main/java/ca/marshallasch/veil/utilities/PeerDiscoveryManager.java
  app/src/main/java/ca/marshallasch/veil/utilities/Util.java
  app/src/main/proto/sync.proto
  app/src/main/res/menu/main_menu.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/ca/marshallasch/veil/HashTableStoreTest.java
Labels: Status: Review Needed

#66 58 update unit tests
  app/src/androidTest/java/ca/marshallasch/veil/ExampleInstrumentedTest.java
  app/src/androidTest/java/ca/marshallasch/veil/database/DatabaseTest.java
  app/src/main/java/ca/marshallasch/veil/CommentListAdapter.java
  app/src/main/java/ca/marshallasch/veil/FragmentViewPost.java
  app/src/main/java/ca/marshallasch/veil/database/Database.java
  app/src/main/java/ca/marshallasch/veil/database/KnownPostsContract.java
  app/src/main/java/ca/marshallasch/veil/database/Migrations.java
  app/src/main/java/ca/marshallasch/veil/utilities/Util.java
  app/src/test/java/ca/marshallasch/veil/ExampleUnitTest.java
  app/src/test/java/ca/marshallasch/veil/HashTableStoreTest.java
Labels: Status: Review Needed

#71 61 add comment ui
  app/build.gradle
  app/src/main/java/ca/marshallasch/veil/FragmentAddComment.java
  app/src/main/java/ca/marshallasch/veil/FragmentViewPost.java
  app/src/main/java/ca/marshallasch/veil/MainActivity.java
  app/src/main/res/anim/do_nothing.xml
  app/src/main/res/anim/slide_in_down.xml
  app/src/main/res/anim/slide_in_up.xml
  app/src/main/res/drawable/commentbar.png
  app/src/main/res/layout/fragment_add_comment.xml
  app/src/main/res/layout/fragment_discover_forums.xml
  app/src/main/res/layout/fragment_view_post.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Needed

#76 75 add comment logic
  app/src/main/java/ca/marshallasch/veil/CommentListAdapter.java
  app/src/main/java/ca/marshallasch/veil/Data.java
  app/src/main/java/ca/marshallasch/veil/DataStore.java
  app/src/main/java/ca/marshallasch/veil/ForumStorage.java
  app/src/main/java/ca/marshallasch/veil/FragmentAddComment.java
  app/src/main/java/ca/marshallasch/veil/FragmentViewPost.java
  app/src/main/java/ca/marshallasch/veil/HashTableStore.java
  app/src/main/java/ca/marshallasch/veil/comparators/CommentComparator.java
  app/src/main/java/ca/marshallasch/veil/comparators/PostPairComparator.java
  app/src/main/java/ca/marshallasch/veil/utilities/Util.java
  app/src/main/res/layout/fragment_view_post.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/ca/marshallasch/veil/HashTableStoreTest.java
Labels: Status: Review Needed

#68 65 remember login v2
  app/src/main/java/ca/marshallasch/veil/FragmentDashBoard.java
  app/src/main/java/ca/marshallasch/veil/FragmentLanding.java
  app/src/main/java/ca/marshallasch/veil/FragmentLogin.java
  app/src/main/java/ca/marshallasch/veil/FragmentSignUp.java
  app/src/main/java/ca/marshallasch/veil/MainActivity.java
  app/src/main/java/ca/marshallasch/veil/database/Database.java
  app/src/main/java/ca/marshallasch/veil/utilities/Util.java
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/values/strings.xml
Labels: Status: Review Needed
